arch: ppc64le
if: type = pull_request
dist: focal
os: linux
language: shell

services:
    - docker

before_install:
    - docker pull registry.access.redhat.com/ubi8/ubi:8.5

before_script:
    - sudo apt-get install jq wget -y
    - curl -H "Accept: application/json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/anup-kodlekere/travis-bs-validator/pulls/$TRAVIS_PULL_REQUEST/files > /tmp/out.json
    - BUILD_SCRIPTS_PR_NUM=$(jq .[0].filename /tmp/out.json | tr -d \")
    - echo $BUILD_SCRIPTS_PR_NUM

matrix:
    include:
        - name: Build-Script
          env: build-script-repo
          script:
            - git clone https://github.com/ppc64le/build-scripts/
            - sudo apt update -y && sudo apt-get install file -y
            - pip3 install requests
            - pip3 install docker
            - python3 build-scripts/script/validate_builds.py $BUILD_SCRIPTS_PR_NUM &
            - SCRIPT_PID=$!;while ps -p $SCRIPT_PID > /dev/null;do echo "$SCRIPT_PID is running"; sleep 60; done; wait $SCRIPT_PID; my_pid_status=$?; travis_terminate $my_pid_status
